# Will first create the database and provision it correctly
# Then sets up the app to communicate with it correctly
---

#####################
# DATABASE
- name: installs mongodb 3.2.20, makes it listen to 0.0.0.0 and starts+enables it
  hosts: db_server
  gather_facts: yes
  become: true

  tasks:
  - name: add the GPG key for mongoDB 3.2
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present
      
  - name: create a /etc/apt/sources.list.d/mongodb-org-3.2.list file
    copy:
      dest: "/etc/apt/sources.list.d/mongodb-org-3.2.list"
      content: |
        deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse

  - name: install mongodb 3.2.20
    apt:
      name: 
      - mongodb-org=3.2.20
      - mongodb-org-server=3.2.20
      - mongodb-org-mongos=3.2.20
      - mongodb-org-tools=3.2.20
      state: present
      update_cache: yes

  - name: change the bind ip in /etc/mongod.conf
    replace:
      path: /etc/mongod.conf
      regexp: '^(  bindIp: 127.0.0.1)$'
      replace: '  bindIp: 0.0.0.0'

  - name: enable and start mongod
    systemd:
      name: mongod
      state: started
      enabled: yes


#####################
# APP
- name: prepares the app environment and runs the app
  hosts: app_server
  gather_facts: yes
  vars:
    database_priv_ip: 172.31.40.107

  tasks:
  - name: get the needed files for nodejs
    become: true
    get_url:
      url: https://deb.nodesource.com/setup_12.x
      dest: ~/
      mode: 755

  - name: run the nodejs bash script so nodejs can be installed
    become: true
    shell:
      cmd: ~/setup_12.x

  - name: install nodejs, nginx
    become: true
    apt:
      name: 
        - nodejs
        - nginx
      state: present
      update_cache: yes

  - name: install pm2 using npm
    become: true
    npm: 
      name: pm2
      global: yes
      state: present

  - name: copy in the config-file for reverse proxy
    become: true
    copy:
      src: ~/playbooks/app-files/reverse-proxy.conf
      dest: /etc/nginx/sites-available/reverse-proxy.conf

  - name: create symlink from copied file to default
    become: true
    file:
      src: /etc/nginx/sites-available/reverse-proxy.conf
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: restart nginx for new config to take place
    become: true
    service:
      name: nginx
      state: restarted

# sets the DB_HOST env variable
  - name: set the DB_HOST variable within .bashrc
    lineinfile:
      path: /home/ubuntu/.bashrc
      line: export DB_HOST={{ database_priv_ip }}
    become: true

  - name: create DB_HOST environment variable
    shell: export DB_HOST={{ database_priv_ip }}

# copies app files, installs dependencies and starts the app
  - name: copy the app folders over to the host
    copy: 
      src: ~/playbooks/app-files/app
      dest: ~/

  - name: ensures node_modules and package-lock.json are not present so we can use seeds
    file: 
      path: 
        - ~/app/node_modules
        - ~/app/package-lock.json
      state: absent

  - name: npm install the dependencies from package.json
    shell:
      chdir: ~/app
      cmd: npm install

  - name: stops any app running with pm2 and starts it again
    shell: |
      pm2 kill
      pm2 start app.js --update-env
      export DB_HOST={{ database_priv_ip }}
      pm2 reload app.js --update-env
    args:
      chdir: ~/app
